Repository KAIST-IS521/2018s-onion-team3, pull requests merged in 2018-04, with the labels that each got.

#54 Issue53 buffer
  onionMessenger/message.cpp
  onionMessenger/onionui.cpp
  onionMessenger/sockthread.cpp
Labels: Priority: Medium, Status: Review needed, Type: Online

#56 Set random padding field name to "padding"
  onionMessenger/message.cpp
Labels: Status: Completed

#58 Issue55 newchat
  onionMessenger/common.cpp
  onionMessenger/common.h
  onionMessenger/keymanager.cpp
  onionMessenger/messenger.cpp
  onionMessenger/onionui.cpp
  onionMessenger/sockthread.cpp
Labels: Priority: Medium, Status: Review needed, Type: Online

#59 Add feature - group messaging
  onionMessenger/common.h
  onionMessenger/keymanager.cpp
  onionMessenger/onionui.cpp
  onionMessenger/pgpmanager.cpp
  onionMessenger/sockthread.cpp
Labels: Priority: High, Status: Review needed, Type: Online, Type: enhancement

#62 Format string bug
  onionMessenger/onionui.cpp
Labels: Bug

#63 unsanitized passphrase
  onionMessenger/pgpmanager.cpp
Labels: Bug

#65 improper function ReplaceAll causes denial of service
  onionMessenger/pgpmanager.cpp
Labels: Bug

#64 command injection in PGPManager::Enc
  onionMessenger/pgpmanager.cpp
Labels: Bug
