Repository KAIST-IS521/2018s-onion-team3, pull requests merged in 2018-03, with the labels that each got.

#17 Issue10 pitchme
  PITCHME.md
Labels: Priority: Low, Status: Completed, Type: Online, Type: enhancement

#21 Issue18 docker
  AutoDocker.sh
  Dockerfile
  README.md
  startMessenger.sh
Labels: Priority: Medium, Status: In progress, Type: Online

#20 Issue15 sockserver
  .gitignore
  onionMessenger/common.h
  onionMessenger/main.cpp
  onionMessenger/message.cpp
  onionMessenger/message.h
  onionMessenger/messenger.cpp
  onionMessenger/onionMessenger.pro
  onionMessenger/sockserver.cpp
  onionMessenger/sockserver.h
  onionMessenger/sockthread.cpp
  onionMessenger/sockthread.h
Labels: Priority: Low, Status: Review needed, Type: Online, Type: enhancement

#25 Issue22 json
  onionMessenger/common.h
  onionMessenger/json.hpp
  onionMessenger/message.cpp
  onionMessenger/message.h
  onionMessenger/onionMessenger.pro
Labels: Priority: Medium, Status: Review needed, Type: Online, Type: enhancement

#29 Issue26 jsonify
  onionMessenger/common.h
  onionMessenger/message.cpp
  onionMessenger/message.h
  onionMessenger/messenger.cpp
  onionMessenger/onionMessenger.pro
  onionMessenger/onionui.cpp
  onionMessenger/onionui.h
Labels: Priority: Medium, Status: Review needed, Type: Online, Type: enhancement

#31 Issue19 proto
  onionMessenger/common.cpp
  onionMessenger/keymanager.cpp
  onionMessenger/keymanager.h
  onionMessenger/message.cpp
  onionMessenger/message.h
  onionMessenger/messenger.cpp
  onionMessenger/onionui.cpp
  onionMessenger/onionui.h
  onionMessenger/sockthread.cpp
Labels: Priority: High, Status: Completed

#32 Issue23 ui
  onionMessenger/common.cpp
  onionMessenger/common.h
  onionMessenger/onionui.cpp
  onionMessenger/onionui.h
  onionMessenger/sockthread.cpp
Labels: Priority: Medium, Status: Review needed, Type: Online

#36 Issue33 uierror
  onionMessenger/onionui.cpp
Labels: Priority: Medium, Status: Review needed, Type: Online

#39 Issue35 readme
  README.md
Labels: Priority: Low, Status: Completed

#44 Issue34 pgp
  onionMessenger/common.h
  onionMessenger/keymanager.cpp
  onionMessenger/keymanager.h
  onionMessenger/main.cpp
  onionMessenger/messenger.cpp
  onionMessenger/messenger.h
  onionMessenger/pgpmanager.cpp
  onionMessenger/pgpmanager.h
Labels: Priority: Medium, Status: Review needed, Type: Online

#46 Issue45 onion
  onionMessenger/common.h
  onionMessenger/keymanager.cpp
  onionMessenger/messenger.cpp
  onionMessenger/onionui.cpp
  onionMessenger/pgpmanager.cpp
  onionMessenger/pgpmanager.h
  onionMessenger/sockthread.cpp
Labels: Status: Completed, Type: enhancement

#47 Issue45 onion
  Dockerfile
  onionMessenger/Makefile
  onionMessenger/common.h
  onionMessenger/keymanager.cpp
  onionMessenger/keymanager.h
  onionMessenger/message.cpp
  onionMessenger/message.h
  onionMessenger/onionMessenger.pro
  onionMessenger/onionui.cpp
  onionMessenger/pgpmanager.cpp
  onionMessenger/sockthread.cpp
  testkey/githubE.key
  testkey/githubE.pub
  testkey/githubF.key
  testkey/githubF.pub
Labels: Priority: Critical, Status: Completed, Type: Online

#49 Issue48 warning
  onionMessenger/main.cpp
  onionMessenger/messenger.cpp
  onionMessenger/onionui.cpp
  onionMessenger/onionui.h
Labels: Priority: Medium, Status: Completed, Type: Online

#50 Issue42 vector
  Dockerfile
  onionMessenger/pgpmanager.cpp
  setup.sh
  startMessenger.sh
Labels: Priority: Medium, Status: Review needed, Type: Online

#51 Issue35 readme
  README.md
  images/onion.jpg
  onionMessenger/githubA.key
  onionMessenger/githubA.pub
  onionMessenger/githubB.key
  onionMessenger/githubB.pub
  onionMessenger/githubC.key
  onionMessenger/githubC.pub
  onionMessenger/githubD.key
  onionMessenger/githubD.pub
Labels: Priority: High, Status: Completed, Type: Online

#52 Issue42 vector
  onionMessenger/common.cpp
  onionMessenger/common.h
  onionMessenger/messenger.cpp
  onionMessenger/onionui.cpp
  onionMessenger/onionui.h
  onionMessenger/pgpmanager.cpp
  onionMessenger/sockthread.cpp
Labels: Priority: Medium, Status: Review needed, Type: Online
